FROM node:lts-buster-slim

WORKDIR /src
COPY package*.json ./

ENV NUXT_HOST=0.0.0.0
ENV PATH /node_modules/.bin:$PATH

RUN npm install
# RUN ln -sf /node_modules /src/node_modules

COPY . .

RUN npm run build

CMD ["npm", "run", "start"]
